---
- name: Validate Telnet accessibility
  gather_facts: false
  connection: local
  hosts: sydonVm

  tasks:
   - name: run show commands
     telnet:
      user: "{{ username }}"
      password: "{{ password }}"
      login_prompt: "Username: "
      prompts:
       - "[>#]"
      commands:
       - echo '1'
     register: output