---
- hosts: sydon
  gather_facts: true
  connection: local

  tasks:
   - name: run show commands
     telnet:
      user: don
      password: DevAdmin123!
      login_prompt: "Username: "
      prompts:
       - "[>#]"
      commands:
       - terminal length 0
       - show version
     register: output