---
- name: Validate Telnet accessibility
  gather_facts: false
  hosts: sydonVm

  tasks:
   - name: run show commands
     telnet:
       user: "{{ username }}"
       password: "{{ password }}"
       login_prompt: "Username: "
       prompts:
         - "[>#]"
       command:
         - echo '1'