- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: my first telnet task
      telnet:
        username: don
        password: DevAdmin123!
        login_prompt: "Username: "
        prompts:
         - "[>#]"        