---
- name: Validate Telnet accessibility
  gather_facts: false
  connection: local
  hosts: "{{ hostname }}"

  tasks:
   - name: run show commands
     telnet:
      user: "{{ username }}"
      password: "{{ password }}"
      login_prompt: "Username: "
      prompts:
       - "[>#]"
      commands:
       - terminal length 0
       - show version
     register: output