---
- hosts: localhost
  gather_facts: true
  connection: local

  tasks:
   - name: run show commands
     telnet:
      host: {{hostname}}
      user: {{username}}
      password: {{password}}
      login_prompt: "Username: "
      prompts:
       - "[>#]"
      commands:
       - terminal length 0
       - show version
     register: output